# Check du lien et des valeurs

In [4]:
%load_ext sql
%sql duckdb:///../../database/data.duckdb
%config SqlMagic.displaylimit = 100

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [2]:
%%sql 
SELECT
   *
FROM
    edc_resultats
LIMIT 2

Running query in 'duckdb:///../../database/data.duckdb'

+--------+---------------+---------------------+-------------+--------------------+--------------------+-----------------+-------------+-----------+--------+--------------------------+------------------+------------+---------+-------------+-----------+--------------+--------------+-------------------+---------------------+
| cddept | referenceprel | cdparametresiseeaux | cdparametre |  libmajparametre   |  libminparametre   | libwebparametre | qualitparam | insituana | rqana  | cdunitereferencesiseeaux | cdunitereference | limitequal | refqual | valtraduite |  casparam | referenceanl | de_partition | de_ingestion_date | de_dataset_datetime |
+--------+---------------+---------------------+-------------+--------------------+--------------------+-----------------+-------------+-----------+--------+--------------------------+------------------+------------+---------+-------------+-----------+--------------+--------------+-------------------+---------------------+
|  001   |  00100119085  |        12DCLE       |     1161    | DICHLOROÉTHANE-1,2 | Dichloroéthane-1,2 |       None      |      N      |     L     | <0,50  |           µg/L           |       133        |  <=3 µg/L  |   None  |     0.0     |  107-06-2 | 00100125759  |     2020     |     2025-02-14    |   20230811-150005   |
|  001   |  00100119085  |         A2H         |     1832    | ATRAZINE-2-HYDROXY | Atrazine-2-hydroxy |       None      |      N      |     L     | <0,020 |           µg/L           |       133        | <=0,1 µg/L |   None  |     0.0     | 2163-68-0 | 00100125759  |     2020     |     2025-02-14    |   20230811-150005   |
+--------+---------------+---------------------+-------------+--------------------+--------------------+-----------------+-------------+-----------+--------+--------------------------+------------------+------------+---------+-------------+-----------+--------------+--------------+-------------------+---------------------+

In [5]:
%%sql 
SELECT DISTINCT
    valtraduite,
    rqana
FROM
    edc_resultats
WHERE
    valtraduite =0 OR valtraduite=1

Running query in 'duckdb:///../../database/data.duckdb'

+-------------+----------------+
| valtraduite |     rqana      |
+-------------+----------------+
|     0.0     |    <0,0050     |
|     0.0     |     <0,050     |
|     0.0     |       <5       |
|     0.0     |     <0,500     |
|     0.0     |     <0,100     |
|     0.0     |      0,00      |
|     0.0     | Aspect normal  |
|     1.0     | Aspect anormal |
|     0.0     |     <8,60      |
|     0.0     |     <0,001     |
|     0.0     |     <0,048     |
|     0.0     |     <3,70      |
|     0.0     |     <3,40      |
|     0.0     |     <0,018     |
|     0.0     |     <0,046     |
|     0.0     |     <7,50      |
|     0.0     |     <7,80      |
|     0.0     |     <5,60      |
|     0.0     |     <4,50      |
|     0.0     |     <0,043     |
|     0.0     |     <7,00      |
|     0.0     |     <6,30      |
|     0.0     |     <9,00      |
|     0.0     |     <7,60      |
|     0.0     |     <8,20      |
|     0.0     |     <0,14      |
|     0.0     |     <9,80      |
|     0.0     |     <1,00      |
|     0.0     |     <0,220     |
|     0.0     |     <0,450     |
|     0.0     |       <6       |
|     0.0     |     <0,087     |
|     0.0     |     <0,025     |
|     0.0     |    <0,0021     |
|     0.0     |    <0,0011     |
|     0.0     |     <0,12      |
|     0.0     |     <12,2      |
|     0.0     |     <0,033     |
|     0.0     |     <0,031     |
|     0.0     |     <0,059     |
|     0.0     |       <7       |
|     0.0     |     <0,021     |
|     0.0     |     <0,032     |
|     0.0     |     <0,058     |
|     0.0     |     <0,129     |
|     0.0     |     <0,035     |
|     0.0     |     <0,26      |
|     0.0     |     <0,072     |
|     0.0     |      <9,9      |
|     0.0     |     <0,27      |
|     0.0     |     <0,24      |
|     0.0     |      <8,1      |
|     0.0     |     <0,09      |
|     0.0     |      <7,8      |
|     0.0     |      <8,7      |
|     0.0     |      <5,5      |
|     0.0     |      <5,4      |
|     1.0     |    PRESENCE    |
|     0.0     |    <0,0125     |
|     0.0     |      <0,6      |
|     0.0     |      <7,4      |
|     0.0     |     <0,29      |
|     0.0     |     <0,31      |
|     0.0     |      <3,2      |
|     0.0     |     <11,70     |
|     0.0     |     <0,47      |
|     0.0     |     <0,34      |
|     1.0     |      OUI       |
|     0.0     |      <5,7      |
|     0.0     |     <5,57      |
|     0.0     |     <5,87      |
|     0.0     |     <5,69      |
|     0.0     |     <5,68      |
|     0.0     |     <5,61      |
|     0.0     |     <5,92      |
|     0.0     |     <5,54      |
|     0.0     |     <5,91      |
|     0.0     |     <5,97      |
|     0.0     |     <5,16      |
|     0.0     |     <5,78      |
|     0.0     |     <5,72      |
|     0.0     |     <5,00      |
|     0.0     |     <6,12      |
|     0.0     |     <8,00      |
|     0.0     |     <9,40      |
|     0.0     |    <0,0333     |
|     0.0     |     <0,383     |
|     0.0     |    <0,0157     |
|     0.0     |     <0,223     |
|     0.0     |    <0,0613     |
|     0.0     |    <0,0227     |
|     0.0     |     <0,483     |
|     0.0     |     <0,113     |
|     0.0     |     <0,107     |
|     0.0     |     <0,643     |
|     0.0     |    <0,0473     |
|     0.0     |    <0,0373     |
|     0.0     |     <0,101     |
|     0.0     |     <0,171     |
|     0.0     |     <4,97      |
+-------------+----------------+
Truncated to displaylimit of 100.

In [7]:
%%sql 
SELECT DISTINCT
    valtraduite,
    rqana
FROM
    edc_resultats
WHERE
    valtraduite=1

Running query in 'duckdb:///../../database/data.duckdb'

+-------------+------------------------------------+
| valtraduite |               rqana                |
+-------------+------------------------------------+
|     1.0     |           Aspect anormal           |
|     1.0     |                OUI                 |
|     1.0     |              PRESENCE              |
|     1.0     |                >1,0                |
|     1.0     |                 1,                 |
|     1.0     | Présence d'un dispositif de trait. |
|     1.0     |    Branchement public en plomb     |
|     1.0     |       Légèrement incrustante       |
|     1.0     |                1,00                |
|     1.0     |               1,000                |
|     1.0     |      Présence cyanobactéries       |
|     1.0     |  Canalisation intérieure en plomb  |
|     1.0     |                 1                  |
|     1.0     |         Changement anormal         |
|     1.0     |                 >1                 |
|     1.0     |                1,0                 |
|     1.0     |               1,0000               |
|     1.0     |  Perception d'une odeur sulfurée   |
+-------------+------------------------------------+

In [6]:
%%sql 
SELECT DISTINCT
    valtraduite,
    rqana
FROM
    edc_resultats

Running query in 'duckdb:///../../database/data.duckdb'

+-------------+---------------+
| valtraduite |     rqana     |
+-------------+---------------+
|     0.0     |     <0,050    |
|    37.23    |     37,23     |
|     0.0     |     <0,100    |
|     0.05    |     0,050     |
|     0.0     | Aspect normal |
|     89.9    |      89,9     |
|    565.0    |      565      |
|     0.17    |      0,17     |
|     8.1     |      8,1      |
|     0.2     |      0,2      |
|     0.78    |      0,78     |
|     0.11    |      0,11     |
|     1.6     |      1,6      |
|     0.0     |     <0,500    |
|     0.8     |      0,80     |
|     0.7     |      0,7      |
|     1.4     |      1,4      |
|     7.7     |      7,7      |
|     18.2    |      18,2     |
|     1.38    |      1,38     |
|    0.129    |     0,129     |
|    120.6    |     120,6     |
|    754.0    |      754      |
|     14.8    |      14,8     |
|     0.37    |      0,37     |
|     0.3     |      0,3      |
|     9.0     |       9       |
|     2.2     |      2,2      |
|    0.107    |     0,107     |
|    655.0    |      655      |
|     0.09    |      0,09     |
|    378.0    |     378,0     |
|     10.1    |      10,1     |
|     7.3     |      7,3      |
|     14.9    |      14,9     |
|     0.14    |      0,14     |
|     98.9    |      98,9     |
|    686.0    |      686      |
|     0.28    |      0,28     |
|     2.1     |      2,10     |
|     0.38    |      0,38     |
|     22.7    |      22,7     |
|     12.1    |      12,1     |
|     7.26    |      7,26     |
|    0.021    |     0,021     |
|    657.0    |      657      |
|     0.0     |     <1,00     |
|     0.0     |       <5      |
|     0.0     |      0,00     |
|     9.9     |      9,90     |
|     0.18    |      0,18     |
|    0.011    |     0,011     |
|    498.0    |      498      |
|     2.5     |      2,50     |
|     13.0    |       13      |
|     21.0    |       21      |
|     7.6     |      7,6      |
|    342.0    |      342      |
|     4.0     |       4       |
|     23.0    |       23      |
|    466.0    |      466      |
|     66.0    |       66      |
|     26.0    |       26      |
|    24.19    |     24,19     |
|     1.3     |      1,3      |
|     12.5    |      12,5     |
|    272.0    |      272      |
|    402.0    |      402      |
|     98.0    |      98,0     |
|     9.1     |      9,1      |
|    25.35    |     25,35     |
|     0.13    |      0,13     |
|    103.0    |      103      |
|     0.31    |      0,31     |
|     16.4    |      16,4     |
|    479.0    |      479      |
|     18.1    |      18,1     |
|     5.0     |       5       |
|    970.0    |      970      |
|     0.0     |     <0,001    |
|     48.0    |       48      |
|     31.0    |       31      |
|     11.0    |     11,00     |
|     0.29    |      0,29     |
|    784.0    |      784      |
|     20.6    |      20,6     |
|    209.0    |      209      |
|    415.0    |      415      |
|     1.7     |      1,7      |
|    230.0    |      230      |
|     0.49    |      0,49     |
|    411.0    |      411      |
|    500.0    |      500      |
|    369.0    |      369      |
|    518.0    |      518      |
|    630.0    |      630      |
|     15.5    |      15,5     |
|    721.0    |      721      |
|    371.0    |      371      |
|     16.9    |      16,9     |
+-------------+---------------+
Truncated to displaylimit of 100.