# Tache 177 - Resultats PFAS UDI ANNUEL

---

#### Objectif : ajout des résultats PFAS par UDI par années

#### Allez vers la fin pour voir le résultat final et les tests

In [118]:
%reload_ext sql
%sql duckdb:///../../database/data.duckdb
%config SqlMagic.displaylimit = 20
%config SqlMagic.named_parameters="enabled"

The 'toml' package isn't installed. To load settings from pyproject.toml or ~/.jupysql/config, install with: pip install toml

In [ ]:
%%sql

SELECT *
FROM int__resultats_udi_communes
WHERE categorie = 'pfas'
LIMIT 5

In [ ]:
%%sql

SELECT DISTINCT referenceprel, cdparametresiseeaux, cdreseau, inseecommune, COUNT(*) AS nb_analyses
FROM int__resultats_udi_communes
WHERE categorie = 'pfas'
GROUP BY referenceprel, cdparametresiseeaux, cdreseau, inseecommune
HAVING COUNT(*) > 1

In [ ]:
%%sql

-- Nombre de résultats PFAS chaque année, doublons compris (UDI et communes)

WITH pfas_prels AS (SELECT de_partition
    FROM
        'int__resultats_udi_communes'
    WHERE
        categorie = 'pfas')

SELECT de_partition, COUNT(*)
FROM pfas_prels
GROUP BY de_partition

In [74]:
%%sql --save pfas_results_udi

WITH pfas_prels AS (
    SELECT *
    FROM
        'int__resultats_udi_communes'
    WHERE
        categorie = 'pfas'),

deduplicated AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY cdreseau, referenceprel, cdparametresiseeaux, datetimeprel
            ORDER BY cdreseau  -- arbitrary choice
        ) AS row_num
    FROM pfas_prels
)

-- Obtention des résultats PFAS par UDI (cdreseau), avec suppression des doublons dus aux communes
SELECT * EXCLUDE (row_num)
FROM deduplicated
WHERE row_num = 1

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
| referenceprel | cdparametresiseeaux | limitequal | de_partition | valtraduite |   limitequal_float  | unite | categorie |  cdreseau | inseecommune |     datetimeprel    |
+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
|  04500164697  |         PFBS        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000553 |    45331     | 2025-02-24 10:26:00 |
|  04500164697  |         PFNA        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000553 |    45331     | 2025-02-24 10:26:00 |
|  04500164697  |        PFTRDS       |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000553 |    45331     | 2025-02-24 10:26:00 |
|  04500164283  |        PFPEA        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000562 |    45344     | 2025-01-23 09:27:00 |
|  04500164283  |        PFTRDA       |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000562 |    45344     | 2025-01-23 09:27:00 |
|  04500164283  |        SPFAS        | <=0,1 µg/L |     2025     |    0.000    | 0.10000000149011612 |  µg/L |    pfas   | 045000562 |    45344     | 2025-01-23 09:27:00 |
|  04500164200  |         PFNS        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000569 |    45259     | 2025-01-20 09:22:00 |
|  04500164558  |        PFDODA       |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000571 |    45150     | 2025-02-11 08:55:00 |
|  04500164166  |        PFHPS        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000583 |    45083     | 2025-01-17 10:34:00 |
|  04500164166  |        PFPEA        |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000583 |    45275     | 2025-01-17 10:34:00 |
|  04500164166  |        PFTRDA       |    None    |     2025     |    0.000    |         None        |  None |    pfas   | 045000583 |    45279     | 2025-01-17 10:34:00 |
|  04500163183  |         PFBA        |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000604 |    45247     | 2024-10-30 09:36:00 |
|  04500163183  |         PFBS        |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000604 |    45068     | 2024-10-30 09:36:00 |
|  04500163736  |        PFPEA        |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000604 |    45068     | 2024-12-06 10:30:00 |
|  04500163736  |        PFUNDS       |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000604 |    45068     | 2024-12-06 10:30:00 |
|  04500162347  |         PFDA        |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000605 |    45338     | 2024-08-28 09:21:00 |
|  04500162347  |        SPFAS        | <=0,1 µg/L |     2024     |    0.000    | 0.10000000149011612 |  µg/L |    pfas   | 045000605 |    45208     | 2024-08-28 09:21:00 |
|  04500163182  |        PFUNA        |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000605 |    45208     | 2024-10-30 11:20:00 |
|  04500163735  |        PFUNDS       |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000605 |    45208     | 2024-12-06 09:45:00 |
|  04500163741  |        PFDODA       |    None    |     2024     |    0.000    |         None        |  None |    pfas   | 045000605 |    45004     | 2024-12-06 10:50:00 |
+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
Truncated to displaylimit of 20.

In [86]:
%%sql --save pfas_results_udi_vs

WITH pfas_results AS (
    SELECT *
    FROM
        'int__resultats_udi_communes'
    WHERE
        categorie = 'pfas'),

deduplicated_pfas AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY cdreseau, referenceprel, cdparametresiseeaux, datetimeprel
            ORDER BY cdreseau  -- arbitrary choice
        ) AS row_num
    FROM pfas_results
),

valeurs_sanitaires (cdparametresiseeaux, valeur_sanitaire) AS (
    VALUES
        ('PFOA', 0.075),
        ('PFHPA', 0.075),
        ('PFHXA', 960),
        ('PFPEA', 960),
        ('PFBA', 72),
        ('PFBS', 240),
        ('PFOS', 0.18),
        ('PFHXS', 12)
        -- TODO : vérifier unicité de cdparametresiseeaux
)

SELECT
    referenceprel,
    cdreseau,
    dp.cdparametresiseeaux,
    de_partition AS annee,
    datetimeprel,
    valtraduite,
    vs.valeur_sanitaire,
    unite,
    categorie
FROM deduplicated_pfas AS dp
LEFT JOIN valeurs_sanitaires AS vs
    ON dp.cdparametresiseeaux = vs.cdparametresiseeaux
WHERE row_num = 1

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+---------------+-----------+---------------------+-------+---------------------+-------------+------------------+-------+-----------+
| referenceprel |  cdreseau | cdparametresiseeaux | annee |     datetimeprel    | valtraduite | valeur_sanitaire | unite | categorie |
+---------------+-----------+---------------------+-------+---------------------+-------------+------------------+-------+-----------+
|  06900167774  | 069000229 |         PFBS        |  2024 | 2024-10-15 09:24:00 |    0.000    |     240.000      |  None |    pfas   |
|  06900163179  | 069000236 |        PFPEA        |  2024 | 2024-02-12 08:41:00 |    0.002    |     960.000      |  None |    pfas   |
|  06900166081  | 069000236 |        PFHXA        |  2024 | 2024-08-26 09:10:00 |    0.000    |     960.000      |  None |    pfas   |
|  06900166081  | 069000236 |         PFOS        |  2024 | 2024-08-26 09:10:00 |    0.003    |      0.180       |  None |    pfas   |
|  06900164688  | 069000272 |         PFOS        |  2024 | 2024-05-27 08:30:00 |    0.001    |      0.180       |  None |    pfas   |
|  06900166081  | 069000272 |        PFPEA        |  2024 | 2024-08-26 09:10:00 |    0.000    |     960.000      |  None |    pfas   |
|  06900167682  | 069000272 |        PFHPA        |  2024 | 2024-11-18 08:35:00 |    0.000    |      0.075       |  None |    pfas   |
|  06900164688  | 069000273 |         PFBA        |  2024 | 2024-05-27 08:30:00 |    0.000    |      72.000      |  None |    pfas   |
|  06900164688  | 069000273 |         PFOS        |  2024 | 2024-05-27 08:30:00 |    0.001    |      0.180       |  None |    pfas   |
|  06900167682  | 069000273 |        PFPEA        |  2024 | 2024-11-18 08:35:00 |    0.001    |     960.000      |  None |    pfas   |
|  06900168502  | 069000273 |         PFOA        |  2025 | 2025-01-23 08:43:00 |    0.002    |      0.075       |  None |    pfas   |
|  06900163179  | 069000274 |         PFBA        |  2024 | 2024-02-12 08:41:00 |    0.002    |      72.000      |  None |    pfas   |
|  06900164688  | 069000274 |         PFBA        |  2024 | 2024-05-27 08:30:00 |    0.000    |      72.000      |  None |    pfas   |
|  06900167552  | 069000274 |         PFBS        |  2024 | 2024-11-07 08:35:00 |    0.000    |     240.000      |  None |    pfas   |
|  06900166081  | 069000275 |         PFBA        |  2024 | 2024-08-26 09:10:00 |    0.001    |      72.000      |  None |    pfas   |
|  06900163179  | 069000276 |         PFOA        |  2024 | 2024-02-12 08:41:00 |    0.002    |      0.075       |  None |    pfas   |
|  06900166081  | 069000276 |         PFBA        |  2024 | 2024-08-26 09:10:00 |    0.001    |      72.000      |  None |    pfas   |
|  06900166081  | 069000276 |        PFHXA        |  2024 | 2024-08-26 09:10:00 |    0.000    |     960.000      |  None |    pfas   |
|  06900163179  | 069000277 |         PFOS        |  2024 | 2024-02-12 08:41:00 |    0.002    |      0.180       |  None |    pfas   |
|  06900169079  | 069000277 |         PFBA        |  2025 | 2025-02-17 08:39:00 |    0.002    |      72.000      |  None |    pfas   |
+---------------+-----------+---------------------+-------+---------------------+-------------+------------------+-------+-----------+
Truncated to displaylimit of 20.

In [87]:
%%sql --with pfas_results_udi_vs

SELECT
    referenceprel,
    cdreseau,
    cdparametresiseeaux,
    annee,
    COUNT(*) AS nb_analyses
FROM pfas_results_udi_vs
GROUP BY 1, 2, 3, 4
HAVING COUNT(*) > 1
ORDER BY nb_analyses DESC

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+---------------+----------+---------------------+-------+-------------+
| referenceprel | cdreseau | cdparametresiseeaux | annee | nb_analyses |
+---------------+----------+---------------------+-------+-------------+
+---------------+----------+---------------------+-------+-------------+

Plus de doublons dûs aux communes grâce à la window function `ROW_NUMBER()` et au filtre `WHERE row_number = 1`. Cela nous assure d'avoir l'unicité des lignes sur `(referenceprel, cdreseau, cdparametresiseeaux, datetimeprel)`

In [ ]:
%%sql --with pfas_results_udi_vs

SELECT
    referenceprel,
    cdreseau,
    annee,
    COUNT(DISTINCT cdparametresiseeaux) AS nb_parametres,
    -- La somme des 20 PFAS est disponible comme un paramètre (SPFAS)
    MAX(
            CASE WHEN cdparametresiseeaux = 'SPFAS' THEN valtraduite ELSE 0 END
        ) AS sum_20_pfas,
    COUNT(
            DISTINCT CASE
                WHEN cdparametresiseeaux = 'SPFAS' THEN cdparametresiseeaux
            END
        ) AS is_20_pfas,
    SUM(
            CASE
                WHEN
                    cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                    THEN valtraduite
                ELSE 0
            END
        ) AS sum_4_pfas,
    SUM(
            CASE
                WHEN
                    cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                    THEN 1
                ELSE 0
            END
        ) AS nb_4_pfas,
    COUNT(
            DISTINCT CASE
                WHEN
                    valeur_sanitaire IS NOT NULL
                    AND valtraduite IS NOT NULL
                    AND valtraduite >= valeur_sanitaire
                    THEN cdparametresiseeaux
            END
        ) AS nb_pfas_above_limit,
    COUNT(
            DISTINCT CASE
                WHEN valtraduite != 0 THEN cdparametresiseeaux
            END
        ) AS nb_quantified_params
FROM pfas_results_udi_vs
GROUP BY referenceprel, cdreseau, annee
HAVING is_20_pfas = 1

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
| referenceprel |  cdreseau | annee | nb_parametres | sum_20_pfas | is_20_pfas | sum_4_pfas | nb_4_pfas | nb_pfas_above_limit | nb_quantified_params |
+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
|  00800107746  | 008000855 |  2025 |       21      |    2.729    |     1      |   0.813    |     4     |          2          |          12          |
|  00800107747  | 008000855 |  2025 |       21      |    2.711    |     1      |   0.799    |     4     |          2          |          12          |
|  00800107542  | 008000855 |  2025 |       21      |    2.269    |     1      |   0.673    |     4     |          2          |          12          |
|  01300273206  | 013001457 |  2024 |       21      |    0.750    |     1      |   0.577    |     4     |          1          |          11          |
|  01300273540  | 013001457 |  2024 |       21      |    0.684    |     1      |   0.530    |     4     |          1          |          11          |
|  01300273882  | 013001457 |  2025 |       21      |    0.585    |     1      |   0.447    |     4     |          1          |          11          |
|  01300273898  | 013001457 |  2025 |       21      |    0.576    |     1      |   0.396    |     4     |          1          |          11          |
|  01300273793  | 013001457 |  2025 |       21      |    0.544    |     1      |   0.379    |     4     |          1          |          11          |
|  06800175863  | 068006583 |  2024 |       21      |    0.460    |     1      |   0.064    |     4     |          0          |          11          |
|  06800175159  | 068006583 |  2024 |       21      |    0.456    |     1      |   0.056    |     4     |          0          |          11          |
|  01300274520  | 013001457 |  2025 |       21      |    0.455    |     1      |   0.282    |     4     |          1          |          11          |
|  01300272708  | 013001457 |  2024 |       21      |    0.433    |     1      |   0.318    |     4     |          1          |          11          |
|  06800171572  | 068006583 |  2024 |       21      |    0.432    |     1      |   0.056    |     4     |          0          |          11          |
|  06800173563  | 068006583 |  2024 |       21      |    0.424    |     1      |   0.053    |     4     |          0          |          10          |
|  06800175864  | 068001072 |  2024 |       21      |    0.385    |     1      |   0.052    |     4     |          0          |          11          |
|  06800175864  | 068001083 |  2024 |       21      |    0.385    |     1      |   0.052    |     4     |          0          |          11          |
|  06800171808  | 068006583 |  2024 |       21      |    0.376    |     1      |   0.043    |     4     |          0          |          10          |
|  01300274170  | 013001457 |  2025 |       21      |    0.368    |     1      |   0.244    |     4     |          1          |          10          |
|  01300274543  | 013001457 |  2025 |       21      |    0.367    |     1      |   0.244    |     4     |          1          |          10          |
|  06800172154  | 068006583 |  2024 |       20      |    0.366    |     1      |   0.032    |     3     |          0          |          10          |
+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
Truncated to displaylimit of 20.

Ajout des agrégations avant de réaliser le bilan final.

In [120]:
%%sql --save pfas_results_udi_agg

WITH pfas_results AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY cdreseau, referenceprel, cdparametresiseeaux, datetimeprel
            ORDER BY cdreseau
        ) AS row_num
    FROM
        'int__resultats_udi_communes'
    WHERE
        categorie = 'pfas'),

valeurs_sanitaires (cdparametresiseeaux, valeur_sanitaire) AS (
    VALUES
        ('PFOA', 0.075),
        ('PFHPA', 0.075),
        ('PFHXA', 960),
        ('PFPEA', 960),
        ('PFBA', 72),
        ('PFBS', 240),
        ('PFOS', 0.18),
        ('PFHXS', 12)
        -- TODO : vérifier unicité de cdparametresiseeaux
),

pfas_results_udi_vs AS (
    SELECT
        referenceprel,
        cdreseau,
        pr.cdparametresiseeaux,
        de_partition AS annee,
        datetimeprel,
        valtraduite,
        vs.valeur_sanitaire,
        unite,
        categorie
FROM pfas_results AS pr
LEFT JOIN valeurs_sanitaires AS vs
    ON pr.cdparametresiseeaux = vs.cdparametresiseeaux
WHERE row_num = 1
)

SELECT
    referenceprel,
    cdreseau,
    annee,
    COUNT(DISTINCT cdparametresiseeaux) AS nb_parametres,
    -- La somme des 20 PFAS est disponible comme un paramètre (SPFAS)
    MAX(
            CASE WHEN cdparametresiseeaux = 'SPFAS' THEN valtraduite ELSE 0 END
        ) AS sum_20_pfas,
    COUNT(
            DISTINCT CASE
                WHEN cdparametresiseeaux = 'SPFAS' THEN cdparametresiseeaux
            END
        ) AS is_20_pfas,
    SUM(
            CASE
                WHEN
                    cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                    THEN valtraduite
                ELSE 0
            END
        ) AS sum_4_pfas,
    SUM(
            CASE
                WHEN
                    cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                    THEN 1
                ELSE 0
            END
        ) AS nb_4_pfas,
    COUNT(
            DISTINCT CASE
                WHEN
                    valeur_sanitaire IS NOT NULL
                    AND valtraduite IS NOT NULL
                    AND valtraduite >= valeur_sanitaire
                    THEN cdparametresiseeaux
            END
        ) AS nb_pfas_above_limit,
    COUNT(
            DISTINCT CASE
                WHEN valtraduite != 0 THEN cdparametresiseeaux
            END
        ) AS nb_quantified_params
FROM pfas_results_udi_vs
GROUP BY referenceprel, cdreseau, annee
HAVING is_20_pfas = 1

Your query is using one or more of the following snippets: pfas_results_udi_vs. JupySQL does not support snippet expansion within CTEs yet, CTE generation is disabled

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
| referenceprel |  cdreseau | annee | nb_parametres | sum_20_pfas | is_20_pfas | sum_4_pfas | nb_4_pfas | nb_pfas_above_limit | nb_quantified_params |
+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
|  00100143331  | 001000618 |  2024 |       21      |    0.006    |     1      |   0.000    |     4     |          0          |          2           |
|  00100141737  | 001000623 |  2024 |       21      |    0.016    |     1      |   0.011    |     4     |          0          |          7           |
|  00300098553  | 003000360 |  2024 |       21      |    0.105    |     1      |   0.056    |     4     |          0          |          11          |
|  00300099031  | 003000372 |  2024 |       21      |    0.023    |     1      |   0.019    |     4     |          0          |          5           |
|  00300100487  | 003000381 |  2024 |       21      |    0.092    |     1      |   0.037    |     4     |          0          |          12          |
|  00300098549  | 003001374 |  2024 |       21      |    0.031    |     1      |   0.004    |     4     |          0          |          6           |
|  00400146637  | 004000008 |  2024 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400146884  | 004000018 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400146886  | 004000028 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400146875  | 004000106 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400147193  | 004000157 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400147535  | 004000170 |  2025 |       21      |    0.002    |     1      |   0.000    |     4     |          0          |          2           |
|  00400146873  | 004000188 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400146636  | 004000207 |  2024 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400147095  | 004000271 |  2025 |       21      |    0.005    |     1      |   0.000    |     4     |          0          |          2           |
|  00400147040  | 004000295 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400147532  | 004000356 |  2025 |       21      |    0.002    |     1      |   0.000    |     4     |          0          |          2           |
|  00400146756  | 004000377 |  2024 |       21      |    0.022    |     1      |   0.006    |     4     |          0          |          9           |
|  00400146997  | 004000406 |  2025 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
|  00400146380  | 004000494 |  2024 |       21      |    0.000    |     1      |   0.000    |     4     |          0          |          0           |
+---------------+-----------+-------+---------------+-------------+------------+------------+-----------+---------------------+----------------------+
Truncated to displaylimit of 20.

In [134]:
%%sql --with pfas_results_udi_agg

SELECT
    cdreseau,
    annee,
    'pfas' AS categorie,
    'bilan_annuel_' || annee AS periode,
    COUNT(DISTINCT referenceprel) AS nb_prelevements,
    SUM(
        CASE
                WHEN
                        nb_pfas_above_limit > 0
                        THEN 1
                        ELSE 0
        END) AS nb_depassements_vs,
    ROUND((
         SUM(
                CASE
                        WHEN
                                nb_pfas_above_limit > 0
                                THEN 1
                                ELSE 0
                END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_vs,
    SUM(CASE WHEN sum_20_pfas >= 0.1 THEN 1 ELSE 0 END) AS nb_depassements_20_pfas,
    ROUND((
            SUM(CASE WHEN sum_20_pfas >= 0.1 THEN 1 ELSE 0 END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_20_pfas,
    SUM(CASE WHEN sum_4_pfas >= 0.1 THEN 1 ELSE 0 END) AS nb_depassements_4_pfas,
    ROUND((
            SUM(CASE WHEN sum_4_pfas >= 0.1 THEN 1 ELSE 0 END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_4_pfas
FROM pfas_results_udi_agg
GROUP BY cdreseau, annee
ORDER BY nb_prelevements DESC

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
|  cdreseau | annee | categorie |      periode      | nb_prelevements | nb_depassements_vs | ratio_depassements_vs | nb_depassements_20_pfas | ratio_depassements_20_pfas | nb_depassements_4_pfas | ratio_depassements_4_pfas |
+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
| 011000329 |  2024 |    pfas   | bilan_annuel_2024 |        53       |         0          |          0.0          |            12           |            0.23            |           0            |            0.0            |
| 068001072 |  2024 |    pfas   | bilan_annuel_2024 |        25       |         0          |          0.0          |            19           |            0.76            |           0            |            0.0            |
| 074000043 |  2024 |    pfas   | bilan_annuel_2024 |        20       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 011004114 |  2024 |    pfas   | bilan_annuel_2024 |        19       |         0          |          0.0          |            16           |            0.84            |           2            |            0.11           |
| 074001415 |  2023 |    pfas   | bilan_annuel_2023 |        17       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 069000286 |  2024 |    pfas   | bilan_annuel_2024 |        14       |         0          |          0.0          |            3            |            0.21            |           0            |            0.0            |
| 041000728 |  2024 |    pfas   | bilan_annuel_2024 |        13       |         0          |          0.0          |            3            |            0.23            |           0            |            0.0            |
| 074001415 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 038000387 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            4            |            0.33            |           0            |            0.0            |
| 068006363 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            9            |            0.75            |           0            |            0.0            |
| 069000302 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            2            |            0.17            |           0            |            0.0            |
| 069001010 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            10           |            0.83            |           0            |            0.0            |
| 069000295 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            9            |            0.75            |           0            |            0.0            |
| 042000724 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 068001083 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            12           |            1.0             |           0            |            0.0            |
| 068006583 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            11           |            0.92            |           0            |            0.0            |
| 069000321 |  2024 |    pfas   | bilan_annuel_2024 |        11       |         0          |          0.0          |            4            |            0.36            |           0            |            0.0            |
| 068001081 |  2024 |    pfas   | bilan_annuel_2024 |        11       |         0          |          0.0          |            11           |            1.0             |           0            |            0.0            |
| 038001203 |  2023 |    pfas   | bilan_annuel_2023 |        11       |         0          |          0.0          |            9            |            0.82            |           0            |            0.0            |
| 045000474 |  2024 |    pfas   | bilan_annuel_2024 |        11       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
Truncated to displaylimit of 20.

Ajout de la dernière modification pour obtenir une ligne par couple (cdreseau, annee), qui aggrege le nombre de prélèvements réalisés sur chaque année, le nombre de dépassements (valeurs sanitaires, somme 20 pfas, somme 4 pfas), et le ratio sur le nombre de prélèvements.

---

## RÉSULTAT FINAL

In [135]:
%%sql --save resultats_pfas_udi_annuel

WITH pfas_results AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY cdreseau, referenceprel, cdparametresiseeaux, datetimeprel
            ORDER BY cdreseau
        ) AS row_num
    FROM
        'int__resultats_udi_communes'
    WHERE
        categorie = 'pfas'),

valeurs_sanitaires (cdparametresiseeaux, valeur_sanitaire) AS (
    VALUES
        ('PFOA', 0.075),
        ('PFHPA', 0.075),
        ('PFHXA', 960),
        ('PFPEA', 960),
        ('PFBA', 72),
        ('PFBS', 240),
        ('PFOS', 0.18),
        ('PFHXS', 12)
        -- TODO : vérifier unicité de cdparametresiseeaux
),

pfas_results_udi_vs AS (
    SELECT
        referenceprel,
        cdreseau,
        pr.cdparametresiseeaux,
        de_partition AS annee,
        datetimeprel,
        valtraduite,
        vs.valeur_sanitaire,
        unite,
        categorie
    FROM pfas_results AS pr
    LEFT JOIN valeurs_sanitaires AS vs
        ON pr.cdparametresiseeaux = vs.cdparametresiseeaux
    WHERE row_num = 1
),

pfas_results_udi_agg AS (
    SELECT
        referenceprel,
        cdreseau,
        annee,
        COUNT(DISTINCT cdparametresiseeaux) AS nb_parametres,
        -- La somme des 20 PFAS est disponible comme un paramètre (SPFAS)
        MAX(
                CASE WHEN cdparametresiseeaux = 'SPFAS' THEN valtraduite ELSE 0 END
            ) AS sum_20_pfas,
        COUNT(
                DISTINCT CASE
                    WHEN cdparametresiseeaux = 'SPFAS' THEN cdparametresiseeaux
                END
            ) AS is_20_pfas,
        SUM(
                CASE
                    WHEN
                        cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                        THEN valtraduite
                    ELSE 0
                END
            ) AS sum_4_pfas,
        SUM(
                CASE
                    WHEN
                        cdparametresiseeaux IN ('PFOA', 'PFOS', 'PFNA', 'PFHXS')
                        THEN 1
                    ELSE 0
                END
            ) AS nb_4_pfas,
        COUNT(
                DISTINCT CASE
                    WHEN
                        valeur_sanitaire IS NOT NULL
                        AND valtraduite IS NOT NULL
                        AND valtraduite >= valeur_sanitaire
                        THEN cdparametresiseeaux
                END
            ) AS nb_pfas_above_limit,
        COUNT(
                DISTINCT CASE
                    WHEN valtraduite != 0 THEN cdparametresiseeaux
                END
            ) AS nb_quantified_params
    FROM pfas_results_udi_vs
    GROUP BY referenceprel, cdreseau, annee
    HAVING is_20_pfas = 1
)

SELECT
    cdreseau,
    annee,
    'pfas' AS categorie,
    'bilan_annuel_' || annee AS periode,
    COUNT(DISTINCT referenceprel) AS nb_prelevements,
    SUM(
        CASE
                WHEN
                        nb_pfas_above_limit > 0
                        THEN 1
                        ELSE 0
        END) AS nb_depassements_vs,
    ROUND((
         SUM(
                CASE
                        WHEN
                                nb_pfas_above_limit > 0
                                THEN 1
                                ELSE 0
                END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_vs,
    SUM(CASE WHEN sum_20_pfas >= 0.1 THEN 1 ELSE 0 END) AS nb_depassements_20_pfas,
    ROUND((
            SUM(CASE WHEN sum_20_pfas >= 0.1 THEN 1 ELSE 0 END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_20_pfas,
    SUM(CASE WHEN sum_4_pfas >= 0.1 THEN 1 ELSE 0 END) AS nb_depassements_4_pfas,
    ROUND((
            SUM(CASE WHEN sum_4_pfas >= 0.1 THEN 1 ELSE 0 END)
            /
            COUNT(DISTINCT referenceprel)
    ),2) AS ratio_depassements_4_pfas
FROM pfas_results_udi_agg
GROUP BY cdreseau, annee
ORDER BY nb_prelevements DESC

Your query is using one or more of the following snippets: pfas_results_udi_agg, pfas_results_udi_vs. JupySQL does not support snippet expansion within CTEs yet, CTE generation is disabled

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
|  cdreseau | annee | categorie |      periode      | nb_prelevements | nb_depassements_vs | ratio_depassements_vs | nb_depassements_20_pfas | ratio_depassements_20_pfas | nb_depassements_4_pfas | ratio_depassements_4_pfas |
+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
| 011000329 |  2024 |    pfas   | bilan_annuel_2024 |        53       |         0          |          0.0          |            12           |            0.23            |           0            |            0.0            |
| 068001072 |  2024 |    pfas   | bilan_annuel_2024 |        25       |         0          |          0.0          |            19           |            0.76            |           0            |            0.0            |
| 074000043 |  2024 |    pfas   | bilan_annuel_2024 |        20       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 011004114 |  2024 |    pfas   | bilan_annuel_2024 |        19       |         0          |          0.0          |            16           |            0.84            |           2            |            0.11           |
| 074001415 |  2023 |    pfas   | bilan_annuel_2023 |        17       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 069000286 |  2024 |    pfas   | bilan_annuel_2024 |        14       |         0          |          0.0          |            3            |            0.21            |           0            |            0.0            |
| 041000728 |  2024 |    pfas   | bilan_annuel_2024 |        13       |         0          |          0.0          |            3            |            0.23            |           0            |            0.0            |
| 068006363 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            9            |            0.75            |           0            |            0.0            |
| 069000302 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            2            |            0.17            |           0            |            0.0            |
| 069000295 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            9            |            0.75            |           0            |            0.0            |
| 069001010 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            10           |            0.83            |           0            |            0.0            |
| 042000724 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 068001083 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            12           |            1.0             |           0            |            0.0            |
| 068006583 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            11           |            0.92            |           0            |            0.0            |
| 038000387 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            4            |            0.33            |           0            |            0.0            |
| 074001415 |  2024 |    pfas   | bilan_annuel_2024 |        12       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 068001081 |  2024 |    pfas   | bilan_annuel_2024 |        11       |         0          |          0.0          |            11           |            1.0             |           0            |            0.0            |
| 038001203 |  2023 |    pfas   | bilan_annuel_2023 |        11       |         0          |          0.0          |            9            |            0.82            |           0            |            0.0            |
| 045000474 |  2024 |    pfas   | bilan_annuel_2024 |        11       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
| 069000030 |  2023 |    pfas   | bilan_annuel_2023 |        11       |         0          |          0.0          |            0            |            0.0             |           0            |            0.0            |
+-----------+-------+-----------+-------------------+-----------------+--------------------+-----------------------+-------------------------+----------------------------+------------------------+---------------------------+
Truncated to displaylimit of 20.

---

## TESTS SUR LES RÉSULTATS OBTENUS

In [138]:
%%sql --with resultats_pfas_udi_annuel

SELECT
    annee,
    ROUND(AVG(nb_prelevements),2) AS avg_nb_prel,
    ROUND(AVG(nb_depassements_vs),2) AS avg_nb_dep_vs,
    ROUND(AVG(nb_depassements_20_pfas),2) AS avg_nb_dep_20_pfas,
    ROUND(AVG(nb_depassements_4_pfas),2) AS avg_nb_dep_4_pfas
FROM resultats_pfas_udi_annuel
GROUP BY annee

Running query in 'duckdb:///../../database/data.duckdb'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

+-------+-------------+---------------+--------------------+-------------------+
| annee | avg_nb_prel | avg_nb_dep_vs | avg_nb_dep_20_pfas | avg_nb_dep_4_pfas |
+-------+-------------+---------------+--------------------+-------------------+
|  2022 |     2.75    |      0.03     |        0.66        |        0.03       |
|  2023 |     3.8     |      0.0      |        0.47        |        0.02       |
|  2024 |     2.39    |      0.0      |        0.21        |        0.02       |
|  2025 |     1.19    |      0.01     |        0.03        |        0.01       |
+-------+-------------+---------------+--------------------+-------------------+

---

#### Réalisation de tests sur cdreseau `011000329` (le plus testé concernant les PFAS)

In [140]:
%%sql

SELECT COUNT(DISTINCT referenceprel) AS nb_prelevements
FROM 'int__resultats_udi_communes'
WHERE
    cdreseau = '011000329'
    AND de_partition = 2024
    AND categorie = 'pfas'

Running query in 'duckdb:///../../database/data.duckdb'

+-----------------+
| nb_prelevements |
+-----------------+
|        53       |
+-----------------+

In [143]:
%%sql

SELECT *
FROM 'int__resultats_udi_communes'
WHERE
    cdreseau = '011000329'
    AND de_partition = 2024
    AND cdparametresiseeaux = 'SPFAS'
ORDER BY valtraduite DESC

Running query in 'duckdb:///../../database/data.duckdb'

+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
| referenceprel | cdparametresiseeaux | limitequal | de_partition | valtraduite |   limitequal_float  | unite | categorie |  cdreseau | inseecommune |     datetimeprel    |
+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
|  01100170013  |        SPFAS        | <=0,1 µg/L |     2024     |    0.151    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-02 09:21:00 |
|  01100170030  |        SPFAS        | <=0,1 µg/L |     2024     |    0.139    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-26 13:06:00 |
|  01100170031  |        SPFAS        | <=0,1 µg/L |     2024     |    0.134    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-26 12:37:00 |
|  01100169656  |        SPFAS        | <=0,1 µg/L |     2024     |    0.131    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-12-19 12:06:00 |
|  01100167266  |        SPFAS        | <=0,1 µg/L |     2024     |    0.129    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-07-24 09:39:00 |
|  01100167934  |        SPFAS        | <=0,1 µg/L |     2024     |    0.128    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-09-24 09:42:00 |
|  01100169360  |        SPFAS        | <=0,1 µg/L |     2024     |    0.126    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-10-21 11:46:00 |
|  01100170034  |        SPFAS        | <=0,1 µg/L |     2024     |    0.120    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-26 11:40:00 |
|  01100170033  |        SPFAS        | <=0,1 µg/L |     2024     |    0.107    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-26 12:20:00 |
|  01100167684  |        SPFAS        | <=0,1 µg/L |     2024     |    0.106    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-08-26 10:50:00 |
|  01100169053  |        SPFAS        | <=0,1 µg/L |     2024     |    0.106    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-11-21 11:37:00 |
|  01100166961  |        SPFAS        | <=0,1 µg/L |     2024     |    0.103    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-06-27 09:00:00 |
|  01100165533  |        SPFAS        | <=0,1 µg/L |     2024     |    0.093    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-02-02 10:15:00 |
|  01100167689  |        SPFAS        | <=0,1 µg/L |     2024     |    0.027    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-08-26 09:11:00 |
|  01100171960  |        SPFAS        | <=0,1 µg/L |     2024     |    0.025    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-08-26 08:42:00 |
|  01100167269  |        SPFAS        | <=0,1 µg/L |     2024     |    0.024    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-07-24 11:01:00 |
|  01100171956  |        SPFAS        | <=0,1 µg/L |     2024     |    0.022    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-08-26 09:33:00 |
|  01100171957  |        SPFAS        | <=0,1 µg/L |     2024     |    0.020    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-08-26 08:57:00 |
|  01100170618  |        SPFAS        | <=0,1 µg/L |     2024     |    0.019    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-05-30 11:04:00 |
|  01100171781  |        SPFAS        | <=0,1 µg/L |     2024     |    0.015    | 0.10000000149011612 |  µg/L |    pfas   | 011000329 |    11262     | 2024-07-24 10:30:00 |
+---------------+---------------------+------------+--------------+-------------+---------------------+-------+-----------+-----------+--------------+---------------------+
Truncated to displaylimit of 20.

On a bien 12 valeurs SPFAS ≥ 0.1 !